# -*- coding: utf-8 -*-
"""Book Recommendation System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1foApyO8w-WPV1ziUk8NWmeJJgjav71ug

# **Book Recommendation System**

## Import Library
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""set visual theme"""

sns.set_theme(style="whitegrid")

"""download dataset via GitHub"""

books_url = 'https://raw.githubusercontent.com/zygmuntz/goodbooks-10k/master/books.csv'
ratings_url = 'https://raw.githubusercontent.com/zygmuntz/goodbooks-10k/master/ratings.csv'

books = pd.read_csv(books_url)
ratings = pd.read_csv(ratings_url)

"""menampilkan informasi tentang dataset books"""

books.info()

"""informasi tentang sebaran data setiap kolomnya untuk dataset books"""

books.describe(include='all')

"""menampilkan informasi tentang dataset ratings"""

ratings.info()

"""informasi tentang sebaran data setiap kolomnya untuk dataset ratings"""

ratings.describe(include='all')

"""## **Exploratory Data Analysis (EDA)**

Pengecekan missing value
"""

print("=== Missing Value pada Books ===")
books.isnull().sum()[books.isnull().sum() > 0]

print(f'\nJumlah duplikat pada books: {books.duplicated().sum()}')

print("=== Missing Value pada Ratings ===")
ratings.isnull().sum()[ratings.isnull().sum() > 0]

print(f'\nJumlah duplikat pada ratings: {ratings.duplicated().sum()}')

"""Visualisasi top 10 penulis dengan buku terbanyak"""

top_authors = books['authors'].value_counts().head(10)

plt.figure(figsize=(10,5))
sns.barplot(x=top_authors.values, y=top_authors.index, palette='viridis', hue=top_authors)
plt.title('Top 10 Penulis dengan Jumlah Buku Terbanyak')
plt.xlabel('Jumlah Buku')
plt.ylabel('Penulis')
plt.show()

"""Visualisasi top 10 buku dengan rating terbanyak"""

top_rated_books = books.sort_values(by='ratings_count', ascending=False)[['title', 'ratings_count']].head(10)

plt.figure(figsize=(10,5))
sns.barplot(x='ratings_count', y='title', data=top_rated_books, palette='magma', hue='ratings_count')
plt.title('Top 10 Buku Paling Populer Berdasarkan Jumlah Rating')
plt.xlabel('Jumlah Rating Pembaca')
plt.ylabel('Judul Buku')
plt.show()

"""Distribusi skor rating pengguna"""

plt.figure(figsize=(7,4))
sns.countplot(x='rating', data=ratings, palette='Set2', hue='rating')
plt.title('Distribusi Pemberian Skor Rating oleh Pengguna')
plt.xlabel('Skor Rating')
plt.ylabel('Frekuensi')
plt.show()

"""distribusi rata-rata rating buku"""

plt.figure(figsize=(8,4))
sns.histplot(books['average_rating'], bins=30, kde=True, color='teal')
plt.title('Distribusi Rata-rata Rating Buku')
plt.xlabel('Rata-rata Rating')
plt.ylabel('Frekuensi')
plt.show()

"""## **Data Preparation**

### Untuk Content-Based Filtering
"""

from sklearn.feature_extraction.text import TfidfVectorizer

"""memilih kolom penting dan menghapus baris dengan judul atau penulis bernilai null"""

df_cb = books[['book_id', 'title', 'authors', 'average_rating']].dropna().copy()
df_cb.drop_duplicates(subset=['title'], inplace=True)
df_cb

"""membuat representasi fitur gabungan"""

df_cb['content_features'] = df_cb['title'] + ' ' + df_cb['authors']
df_cb.shape

"""Ekstraksi fitur menggunakan TF-IDF Vectorizer"""

tf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tf.fit_transform(df_cb['content_features'])
tfidf_matrix.shape

"""### Untuk Collaborative Filtering

mengambil sampel 100.000 data rating secara acak untuk efisiensi komputasi
"""

ratings_sample = ratings.sample(n=100000, random_state=42).copy()

"""encoding user_id menjadi indeks integer unik"""

user_ids = ratings_sample['user_id'].unique().tolist()
user_to_user_encoded = {x: i for i, x in enumerate(user_ids)}
user_encoded_to_user = {i: x for i, x in enumerate(user_ids)}
ratings_sample['user'] = ratings_sample['user_id'].map(user_to_user_encoded)

"""encoding book_id menjadi indeks integer unik"""

books_ids = ratings_sample['book_id'].unique().tolist()
book_to_book_encoded = {x: i for i, x in enumerate(books_ids)}
book_encoded_to_book = {i: x for i, x in enumerate(books_ids)}
ratings_sample['book'] = ratings_sample['book_id'].map(book_to_book_encoded)

"""memunculkan data unik user dan book"""

num_users = len(user_to_user_encoded)
num_books = len(book_to_book_encoded)
print(f'Jumlah sampel user unik: {num_users}')
print(f'Jumlah sampel buku unik: {num_books}')

"""normalisasi nilai rating ke rentang 0 hingga 1"""

min_rating = ratings_sample['rating'].min()
max_rating = ratings_sample['rating'].max()
ratings_sample['rating_norm'] = ratings_sample['rating'].apply(lambda x: (x - min_rating) / (max_rating - min_rating))

"""membagi data latih dan validasi 80/20"""

ratings_sample = ratings_sample.sample(frac=1, random_state=42)
x = ratings_sample[['user', 'book']].values
y = ratings_sample['rating_norm'].values

train_indices = int(0.8 * ratings_sample.shape[0])
x_train, x_val, y_train, y_val = (
    x[:train_indices],
    x[train_indices:],
    y[:train_indices],
    y[train_indices:],
)

print(f"Dimensi x_train: {x_train.shape}, Dimensi x_val: {x_val.shape}")

"""## **Modelling**

### Model Content-Based Filtering
"""

from sklearn.metrics.pairwise import cosine_similarity

"""Menghitung Cosine Similarity antar buku"""

cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

"""Membuat mapping indeks judul buku"""

indices = pd.Series(df_cb.index, index=df_cb['title']).drop_duplicates()

"""fungsi Top-N Recommendation berbasis konten"""

def get_content_based_recommendations(title, cosine_sim=cosine_sim, top_n=10):
  if title not in indices:
    return f"Buku '{title}' tidak ditemukan."

  idx = indices[title]
  sim_scores = list(enumerate(cosine_sim[idx]))
  sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
  sim_scores = sim_scores[1:top_n+1]

  book_indices = [i[0] for i in sim_scores]

  rec_df = df_cb.iloc[book_indices][['title', 'authors', 'average_rating']].copy()
  rec_df['similarity_score'] = [i[1] for i in sim_scores]
  return rec_df

"""Menampilkan karakteristik buku acuan"""

sample_book = 'The Hunger Games (The Hunger Games, #1)'

print("=== Karakteristik Buku Acuan ===")
print("Judul: {}".format(sample_book))
print("Penulis: Suzanne Collins")
print("Average Rating: 4.34")

"""uji coba rekomendasi"""

print("\nTop-10 Rekomendasi Buku Mirip:")
get_content_based_recommendations(sample_book, top_n=10)

"""### Model Collaborative Filtering

import library yang diperlukan
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

"""definisikan arsitektur model RecommenderNet"""

class RecommenderNet(keras.Model):
  def __init__(self, num_users, num_books, embedding_size, **kwargs):
    super(RecommenderNet, self).__init__(**kwargs)
    self.num_users = num_users
    self.num_books = num_books
    self.embedding_size = embedding_size

    # User Embedding & Bias
    self.user_embedding = layers.Embedding(
        num_users,
        embedding_size,
        embeddings_initializer='he_normal',
        embeddings_regularizer=keras.regularizers.l2(1e-6)
    )
    self.user_bias = layers.Embedding(num_users, 1)

    # Book Embedding & Bias
    self.book_embedding = layers.Embedding(
        num_books,
        embedding_size,
        embeddings_initializer='he_normal',
        embeddings_regularizer=keras.regularizers.l2(1e-6)
    )
    self.book_bias = layers.Embedding(num_books, 1)

  def call(self, inputs):
    user_vector = self.user_embedding(inputs[:, 0])
    user_bias = self.user_bias(inputs[:, 0])
    book_vector = self.book_embedding(inputs[:, 1])
    book_bias = self.book_bias(inputs[:, 1])

    # Dot product antara vektor user dan buku
    dot_user_book = tf.tensordot(user_vector, book_vector, 2)

    # Menjumlahkan dot product dengan bias
    x = dot_user_book + user_bias + book_bias

    # Aktivasi sigmoid untuk membatasi output pada skala [0,1]
    return tf.nn.sigmoid(x)

"""Inisialisasi dan Kompilasi Model"""

model = RecommenderNet(num_users, num_books, embedding_size=50)
model.compile(
    loss=tf.keras.losses.BinaryCrossentropy(),
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    metrics=[tf.keras.metrics.RootMeanSquaredError(name='root_mean_squared_error')]
)

"""training model"""

history = model.fit(
    x=x_train,
    y=y_train,
    batch_size=64,
    epochs=15,
    validation_data=(x_val, y_val),
    verbose=1
)

"""## **Evaluasi**

Visualisasi Metrik Evaluasi RMSE & Loss
"""

plt.figure(figsize=(12,4))

plt.subplot(1,2,1)
plt.plot(history.history['root_mean_squared_error'], label='Train RMSE', color='blue')
plt.plot(history.history['val_root_mean_squared_error'], label ='Val RMSE', color='orange')
plt.title('Root Mean Squared Error (RMSE)')
plt.xlabel('Epoch')
plt.ylabel('RMSE')
plt.legend()

plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='Train Loss', color='blue')
plt.plot(history.history['val_loss'], label='Val Loss', color='orange')
plt.title('Binary Crossentropy Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

"""Fungsi rekomendasi buku untuk spesifik user"""

def get_collaborative_recommendations(user_id, top_n=10):
  if user_id not in user_to_user_encoded:
    return f"User dengan ID '{user_id}' tidak ditemukan."

  user_encoded = user_to_user_encoded[user_id]

  books_read_by_user = ratings_sample[ratings_sample['user_id'] == user_id]

  books_not_read = [b for b in book_to_book_encoded.keys() if b not in books_read_by_user['book_id'].values]
  books_not_read_encoded = [book_to_book_encoded[b] for b in books_not_read]

  user_book_array = np.hstack(
      ([[user_encoded]] * len(books_not_read_encoded), np.array(books_not_read_encoded).reshape(-1,1))
  )

  ratings_pred = model.predict(user_book_array, verbose=0).flatten()

  top_indices = ratings_pred.argsort()[-top_n:][::-1]
  recommended_book_ids = [book_encoded_to_book[books_not_read_encoded[i]] for i in top_indices]

  rec_books = books[books['book_id'].isin(recommended_book_ids)][['title', 'authors', 'average_rating']]
  return rec_books

"""uji rekomendasi personal untuk sampel user"""

sample_user_id = ratings_sample['user_id'].iloc[0]

"""Menampilkan buku-buku dengan rating tinggi yang pernah dibaca oleh user target"""

print(f"=== Buku yang Pernah Dibaca & Diberi Rating Tinggi oleh User ID: {sample_user_id} ===")
user_ratings = ratings_sample[ratings_sample['user_id'] == sample_user_id]
top_user_books = user_ratings.sort_values(by='rating', ascending=False).merge(books, on='book_id')
top_user_books[['title', 'authors', 'rating', 'average_rating']].head(5)

print(f"Top-10 Rekomendasi Buku untuk User ID: {sample_user_id}\n")
get_collaborative_recommendations(sample_user_id, top_n=10)

"""Evaluasi Content-Based Filtering menggunakan Precision@K

Menghitung proporsi rekomendasi yang relevan
"""

def evaluate_precision_at_k(recommendations_df, relevant_keywords=["hunger", "suzanne collins"], k=10):
  top_k = recommendations_df.head(k)

  relevant_items = top_k.apply(lambda row: 1 if any(kw in row['title'].lower()
    or kw in row['authors'].lower() for kw in relevant_keywords) else 0, axis=1).sum()
  precision = relevant_items / k
  return precision

"""Uji Precision@10 pada sampel"""

sample_recs = get_content_based_recommendations(sample_book, top_n=10)
precision_score = evaluate_precision_at_k(sample_recs, relevant_keywords=["hunger", "suzanne collins"], k=10)

print(f"Precision@10 untuk rekomendasi {sample_book}: {precision_score * 100:.1f}%")
